### ISSUE TITLE
WP-API

### ISSUE THREAD

**Issue by ServeMe** [pimedia/json-api-user#7]
I notice you mention json-api plugin
can we use this plugin with wp-api plugin
http://v2.wp-api.org/

**Comment by ServeMe** [comment]
after checking the code obviously they have different structure
if you have any help ideas please let me know

**Comment by pimedia** [comment]
No, that's not possible. JSOn API is different plugin from WP API 
    On Saturday, November 25, 2017, 8:59:47 AM GMT+5, ServeMe <notifications@github.com> wrote:  
 
 
I notice you mention json-api plugin
can we use this plugin with wp-api plugin
http://v2.wp-api.org/

**Comment by ServeMe** [comment]
thank you for you time
